### ISSUE TITLE
Finding the most convenient way to login.

### ISSUE THREAD

**Issue by 0xRampey** [OSDLabs/Open-Sesame#1]
After discussing this issue with a few people, I've come to know 3 possible ways to go about this.

1. Keep a desktop icon that logs in for you, whenever you double-click. 
2. Keep a Chrome extension that you can click on.
3. Leave a background process that continuously polls for network state and logs in automatically when you connect to a Wifi. (Gets tricky fast :P)

I'd love it if you guys suggested anything else or possibly, enhancements of the above; considering cross-platform compatibility and a user-friendly approach.

**Comment by SebastinSanty** [comment]
I think we should go with the first option. The second one limits its usage to people who use chrome and as we had discussed, continuously polling the network would consume more battery.

A better plan would be to check, whenever there is a network change and the app activates on its own, else be a double-click one.

@kaivalyar , @kukreja-vikramaditya : Any comments?

**Comment by MridulS** [comment]
I would prefer a chrome add on and firefox extension as installation is way easier and platform independent (windows/linux/macOS).

**Comment by kukreja-vikramaditya** [comment]
Though addons seems interesting, it may be an overkill. It also means at the end I am still opening my browser. I think that option 1 is fine for now.

The network change listener approach is actually the best but the implementation may vary with the OS. The guys who are making the mobile app are working on the same idea. They 'listen' for any network change broadcasts and login accordingly

**Comment by kaivalyar** [comment]
I would stick with my suggestion of the browser extension - for a desktop app that logs a user onto bitsnet - it seems the only likely usage is through the browser. A double click on the desktop leads to user experience like:
1. open laptop
2. double click open-sesame
3. open browser
4. browse

the in-browser extension is better, especilly because i can't think of applications where people would log in to their bitsnet ids but not browse the net after doing so. the user experience would now be:
1. open laptop
2. open browser
3. click open-sesame
4. browse

IMHO, this is more convenient, and cross platform. We lose the safari crowd - but maybe we can figure that out later?

**Comment by Rushi98** [comment]
I use third way.
``` bash
#!/bin/bash
while true
	do
		wget example.com -O 6DFRyBCMWv.html
		# 6DFRyBCMWv.html : a random filename not likely to be used for any other purpose
		l=$(head -n 1 6DFRyBCMWv.html)
		rm 6DFRyBCMWv.html
		i=${l:1:1}
		if [ $i != "!" ]
		# second character of example.com is "!" (<!doctype html>)
		# second character of cyberoam login page is "H" (<HTML>)
		then
			# net gg
			timeout 10 npm start
		else
			sleep 10m
		fi
	done
```

This check internet connectivity every 10 min and tries to reconnect if disconnected.

**Comment by SebastinSanty** [comment]
@prampey . Can you take a look at this?

**Comment by 0xRampey** [comment]
@Rushi98 That seems to be a nice hack to check. However, I have come across a more convenient way to do the same, sans the dirty website checking. 

Hitting this URL: http://captive.apple.com/hotspot-detect.html , gives me a 'Success' if there is an internet connection or an instant redirect to the corresponding login portal. 

This finally hit me one fine morning when I realized my Mac automatically knows when I have a portal to login to. Since this is a universal 'Apple' thing, I suppose all routers knowingly serve a redirect to this request. The above URL definitely redirects faster than ordinary website requests.

**Comment by kaivalyar** [comment]
even phones just "know" when there is a WiFi network to be signed into, and often redirect to the corresponding login portal. Neat solution, @prampey ! :+1:

**Comment by Rushi98** [comment]
Thanks @prampey.
I don't know why ping doesn't work on bpgc network. That would have been a cleaner way.

**Comment by 0xRampey** [comment]
@Rushi98 The router was probably programmed to not accept the kind of packets employed in pings. Anyways, I just committed a skeletal version of the new method. You can test it and tweak it as you like.
