### ISSUE TITLE
Add support for login through WiFi

### ISSUE THREAD

**Issue by DMak21** [OSDLabs/Open-Sesame#5]
URL - https://20.20.2.11/login.html

Request Parameters -
username: f201xxxx
password: xxxxxxxx
buttonClicked: 4

**Comment by 0xRampey** [comment]
@deepeshmakhijani Has this been implemented in code?

**Comment by DMak21** [comment]
Yes..

**Comment by kaivalyar** [comment]
@prampey lets have a convention to mention the PR which solves an issue when closing the issue?

**Comment by DMak21** [comment]
Implementing the code for the second login portal will make Open Sesame specific for our campus whereas it is intended towards Cyberoam users. Hence we had to close the issue..
